stage:
  all:
    - 民家
    - オレゴン
    - ヘレフォード基地
    - クラブハウス
    - 大統領専用機
    - 領事館
    - 銀行
    - 運河
    - 山荘
    - カフェ・ドストフスキー
    - ヨット
    - 国境
    - ファベーラ
    - 高層ビル
    - バートレット大学
    - 海岸線
    - テーマパーク
    - タワー
    - ヴィラ
    - 要塞
    - アウトバック
  esl:
    - オレゴン
    - クラブハウス
    - 領事館
    - 銀行
    - 国境
    - 海岸線
    - ヴィラ